<?php require_once('template/header.phtml'); ?>
<form class="typeOfForm col-4 background-beach-gradient" style="border-radius: 10px;" action="../typeOfHoliday.php" method="post">
    <div class="form-group" style="padding-top: 20px;">
    <label>
        Type of Holiday
    </label>
    <select class="form-control" name="typeOfHoliday">
        <option value="Adventure">
            Adventure
        </option>
        <option value="Family">
            Family
        </option>
        <option value="Relaxed">
            Relaxed
        </option>
        <option value="Budget">
            Budget
        </option>
    </select>
    </div>
    <div class="form-group">
    <label>Destination</label>
    <input type="text" name="destination" class="form-control">
    </div>
    <div class="form-group">
    <label>Food Preference 1: </label>
    <input type="text" name="preference1" class="form-control">
    <label>Food Preference 2: </label>
    <input type="text" name="preference2" class="form-control">
    <label>Food Preference 3: </label>
    <input type="text" name="preference3" class="form-control">
    </div>
    <div class="form-group">
    <label>Duration of Stay</label>
    <input type="number" name="duration" class="form-control">
    </div>
    <div class="form-group">
    <label>Hobbies</label>
    <input type="text" name="hobbies1" class="form-control multipleControl">
    <input type="text" name="hobbies2" class="form-control multipleControl">
    <input type="text" name="hobbies3" class="form-control multipleControl">
    </div>
    <div style="padding-bottom: 20px;">
        <input type="submit" name="submit" value="submit" class="btn-success form-control">
    </div>
</form>
</div>
<?php require_once('template/footer.phtml'); ?>

