<!DOCTYPE html>
<html lang="en">
<head>
    <!--    <title>--><?php //echo $view->pageTitle; ?><!--</title>-->
    <link rel="icon" href="images/logo.png">
    <!--    <meta name="theme-color" content="#48d594">-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <script src="https://code.jquery.com/jquery.js"></script>
    <link rel="stylesheet" href="css/style1.css">
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="js/bootstrap.js"></script>
</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-light beach-blue">
        <div class="header-logo">
            <a href="index.php"><img src="images/logo.png" style="width: 100px" /></a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-expanded="false" aria-controls="navbarTogglerDemo02" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active color-white">
                    <a class="nav-link" href="../../index.php">Home</a>
                </li>
                <li class="nav-item color-white">
                    <a class="nav-link" href="#">Other things</a>
                </li>
                <?php if (isset($_SESSION['email'])) {?>
                <li>
                    <a class="nav-link" href="#">Suggested Itinerary</a>
                </li>
                <li>
                    <a class="nav-link" href="../../treasureHunt.php">Treasure Hunt</a>
                </li>
                <li>
                    <a class="nav-link" href="#">Emergency Services</a>
                </li>
                <?php }?>
            </ul>

            <?php
            if (isset($_SESSION['email'])) {

                echo '<div class="dropdown margin-login margin-r-15">
                           
                      </div>';

                echo '<a class="btn my-2 my-sm-0 margin-lr-30" style="border-color:#fedc07; color:#fedc07" href="logout.php">Logout</a>';
            }
            else
            {
                echo '<a class="btn my-2 my-sm-0" style="border-color:#fedc07; color:#fedc07" href="login.php">Login</a>';;
            }
            ?>

        </div>
    </nav>
</header>



